# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vima.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vima.proto", :syntax => :proto3) do
    add_message "vima.ConfigObject" do
      optional :id, :string, 1
      optional :key, :string, 2
      optional :value, :string, 3
      optional :is_public, :bool, 4
      optional :created_at, :string, 5
      optional :updated_at, :string, 6
    end
    add_message "vima.ConfigCreateRequest" do
      optional :key, :string, 1
      optional :value, :string, 2
      optional :is_public, :bool, 3
    end
    add_message "vima.ConfigCreateResponse" do
      optional :id, :string, 1
      optional :key, :string, 2
      optional :value, :string, 3
      optional :is_public, :bool, 4
      optional :created_at, :string, 5
      optional :updated_at, :string, 6
    end
    add_message "vima.ConfigIndexRequest" do
    end
    add_message "vima.ConfigIndexResponse" do
      repeated :configs, :message, 1, "vima.ConfigObject"
    end
  end
end

module Vima
  ConfigObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigObject").msgclass
  ConfigCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigCreateRequest").msgclass
  ConfigCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigCreateResponse").msgclass
  ConfigIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigIndexRequest").msgclass
  ConfigIndexResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigIndexResponse").msgclass
end
