# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vima.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vima.proto", :syntax => :proto3) do
    add_message "vima.ConfigObject" do
      optional :id, :string, 1
      optional :key, :string, 2
      optional :value, :string, 3
      optional :is_public, :bool, 4
      optional :created_at, :string, 5
      optional :updated_at, :string, 6
    end
    add_message "vima.ConfigSaveRequest" do
      optional :key, :string, 1
      optional :value, :string, 2
      optional :is_public, :bool, 3
    end
    add_message "vima.ConfigSaveResponse" do
      optional :id, :string, 1
      optional :key, :string, 2
      optional :value, :string, 3
      optional :is_public, :bool, 4
      optional :created_at, :string, 5
      optional :updated_at, :string, 6
    end
    add_message "vima.ConfigSearchRequest" do
    end
    add_message "vima.ConfigSearchResponse" do
      repeated :configs, :message, 1, "vima.ConfigObject"
    end
    add_message "vima.ConfigFindRequest" do
      optional :id, :string, 1
    end
  end
end

module Vima
  ConfigObject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigObject").msgclass
  ConfigSaveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigSaveRequest").msgclass
  ConfigSaveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigSaveResponse").msgclass
  ConfigSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigSearchRequest").msgclass
  ConfigSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigSearchResponse").msgclass
  ConfigFindRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vima.ConfigFindRequest").msgclass
end
